"""users table

Revision ID: 4477a6319f35
Revises: f7ac3d27bb1d
Create Date: 2018-10-27 23:15:06.363279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4477a6319f35'
down_revision = 'f7ac3d27bb1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('blinks', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('no_of_sleeps', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['blinks'])
    op.create_unique_constraint(None, 'user', ['no_of_sleeps'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'no_of_sleeps')
    op.drop_column('user', 'blinks')
    # ### end Alembic commands ###
